name: bank_video_app
description: 은행앱 클론 - 터치마다 영상 넘기기
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/videos/video1.mov
    - assets/videos/video2.mov
    - assets/videos/video3.mov
    - assets/videos/video4.mov
    - assets/videos/video5.mov
    - assets/videos/video6.mov
    - assets/videos/video7.mov
    - assets/videos/video8.mov
    - assets/videos/video9.mp4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
