name: bank_video_app
description: 은행앱 클론 - 터치마다 영상 넘기기
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/videos/video1.MOV
    - assets/videos/video2.MOV
    - assets/videos/video3.MOV
    - assets/videos/video4.MOV
    - assets/videos/video5.MOV
    - assets/videos/video6.MOV
    - assets/videos/video7.MOV
    - assets/videos/video8.MOV
    - assets/videos/video9.MOV

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
